# Configuration file specific information
name: app.yaml
descripton : "This is configuration file for the hatchet profilier."

#Configurations for the profilier driver
run_metadata:
  description: "Run on huge file."
debug: false
profile_type: "single"
profile_endpoint: "/usr/WS2/asde/hatchet-datasets/large-hpctoolkit-datasets/"
filename: "db-ampi4-100-8"
numtrials: 1
profiler: "profiler"
run_output_postfix: "nodes"

# vis configurations
vis:
  updateVis: False
